language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script: nosetests

env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
    